tdd/config/routes.rb
Rails.application.routes.draw do
	resources :candidates do
		member do
			post :vote
		end
	end


  get 'bmi' , to: "bmi#index"
  post "bmi/result" ,to: "bmi#result"

	get "/hello_world" ,to: "pages#hello"

	resources :orders do
		collection do
			get :cancelled
		end
	end
	namespace :denial do
  		resources :users do
  			resources :posts
  		end
  	end	


  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
  end
end

tdd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  #scope :available,-> {where(is_available: true)}
  scope :price_over, -> (p){where(["price > ?" , p])}
  #下面是類別方法,跟 上面scope是一樣的東西
  def self.available
    where(is_available: true)
  end
end
#通常我們會把這種所謂的「商業邏輯」盡量放到 Model 裡（「現在可以上架販售的商品」就是一種商業邏輯），除了可增加程式碼的可讀性，也可以在各個地方重複使用。
#在 Rails 的 Model 有提供一種 scope 的寫法可以讓你完成這件事
#通常如果是簡單的條件，我個人會偏好把它放在 scope 裡，如果是比較複雜的條件，則會建議放在類別方法裡

#預設 Scope
#Rails 的 Model 還有提供 default_scope 的方法，可以幫所有的查詢都預設套上這個條件：  default_scope { order('id DESC') }

tdd/app/models/article.rb
class Article < ApplicationRecord
	#validates :title,presences: true
end

tdd/app/models/candidate.rb
class Candidate < ApplicationRecord
	has_many :vote_logs,dependent: :destroy
end

tdd/app/models/cart.rb
class Cart
	attr_reader :items

	def initialize(items = [])
		@items = items
	end

	def add_item(product_id)
		found_item = items.find{|item| item.product_id == product_id}

		if found_item
			found_item.increment
		else
			@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def total_price
		items.reduce(0) {|sum,item| sum + item.price }
	end

	def self.from_hash(hash)
    if hash.nil?
      new []
    else
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["product_id"], item_hash["quantity"])
      }
    end
  end
	def serialize
		all_items = items.map{|item|
			{"product_id" => item.product_id, "quantity" => item.quantity}
		}

		{"items" => all_items}
	end
end

tdd/app/models/cart_item.rb
class CartItem
	attr_reader :product_id , :quantity


	def initialize(product_id,quantity = 1)
		@product_id = product_id
		@quantity = quantity
	end

	def increment(n=1)
		@quantity = @quantity + n
	end

	def product
		Product.find_by(id: product_id)
	end

	def price
		product.price * quantity
	end
end

tdd/app/models/product.rb
class Product < ApplicationRecord
end

tdd/app/models/store.rb
class Store < ApplicationRecord
	belongs_to :user,optional: true
	has_many :ware_houses
	has_many :products,through: :ware_houses
end
#仔細看一下裡面的錯誤訊息是「User must exist」，也就是必須要有「頭」才行，
#這是 Rails 5 之後對 belongs_to 加入的新限制。但如果覺得這樣有點麻煩想要關掉，可在 belongs_to 後面加上 optional: true 的參數：

=begin
2. has_one 跟 belongs_to 方法需要同時設定嗎？
不一定，端看實際需求而定。以我們上面 User 跟 Store 的例子來看，如果不需要「從 Store 反查 User」的功能，那 belongs_to 就不需要設定了。



-----

常見問題
has_many 後面一定要接複數嗎? 設定單數會怎樣?
不會怎樣，只是有點違反 Rails 的慣例，例如我把原來的 has_many :products 改成 has_many :product：

>> store1 = Store.first
  Store Load (0.1ms)  SELECT  "stores".* FROM "stores" ORDER BY "stores"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> #<Store id: 1, title: "太空膠囊公司", ...[略]..., updated_at: "2017-01-02 13:49:11">
然後就發現原來的 products 方法不能用了（因為沒設定了當然不能用）：
=end

tdd/app/models/user.rb
class User < ApplicationRecord
	has_one :store
end

tdd/app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate,counter_cache: true
end

tdd/app/models/ware_house.rb
class WareHouse < ApplicationRecord
  belongs_to :store
  belongs_to :product
end

tdd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

=begin
*all, where, order, limit
使用 all 方法可取得所有資料，取得資料將存放在陣列裡：

Candidate.all
where 方法則會再加上一些條件做為篩選：

Candidate.where("age > 18", gender: "female")
這樣可取得「女性且大於 18 歲」的候選人。但如果要分開兩段寫也是可以：	

-------
*count, average, sum, maximum, minimum
想要知道總共有多少筆數，可使用 count 方法：
使用 sum 或 average 方法就可以請資料庫直接幫我們做計算。
最大值跟最小值也是一樣，千萬不要傻傻的用 all 全部抓出來再跑迴圈或寫什麼排序演算法，直接使用 maximum 或 minimum 方法請資料庫幫你算就好
-----------
CRUD 之 U（Update）
更新資料常用的有 save、update、update_attribute 及 update_attributes 方法：
=end

tdd/app/controllers/bmi_controller.rb
class BmiController < ApplicationController
  def index
  end

  def result #這些params 參數都是使用者從 browser 輸入資料 然後帶入 view.html.erb 然後 從那邊取過來的 params 再帶入 bmi_controller.eb 裡面去做運算。
  	h = params[:body_height].to_f/100
  	w = params[:body_weight].to_f
  	a = params[:age].to_i
  	g = params[:gender].to_i #後面要加入to_i 或者 to_f   ,  不然params 從view 取過來的都是 『字串』 型態

  	@bmi = (w / (h * h)).round(2)
  	@fat_rate = ((1.2 * @bmi) +(0.23 * a - 5.4) - (10.8 * g)).round(2)
  end
end

tdd/app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	 #layout "backend"
	before_action :find_candidate, only: [:edit,:destroy,:update,:votes]
	def index 
		@candidates = Candidate.all
	end

	def new
		@candidate = Candidate.new
	end

	def create
		@candidate = Candidate.new(candidate_params)

		if @candidate.save
			redirect_to candidates_path,notice: "新增候選人成功!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @candidate.update(candidate_params)
			redirect_to candidates_path, notice:"更新資料成功!"
		else
			render :edit
		end
	end

	def destroy
		@candidate.destroy if @candidate
		redirect_to candidates_path,notice: "刪除資料成功!"
	end

	def vote
		@candidate.vote_logs.create(ip_address: request.remote_ip) if @candidate
		#@candidate.increment(:votes)
		#@candidate.save
		redirect_to candidates_path,notice: "完成投票!"
	end

	private
	def candidate_params
		params.require(:candidate).permit(:name,:party,:age,:politics,:votes)
	end
	
	def find_candidate
		@candidate = Candidate.find_by(id: params[:id])
	end
end

tdd/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def hello
		render json: params["name"]
	end
end

tdd/app/helpers/application_helper.rb
module ApplicationHelper
	def user_gender(gender)
	    if gender == 1
	      "男"
	    elsif gender == 0
	      "女"
	    else
	      "不想說"
	    end
	end

	def icon_link_to(label, path, icon)
	    link_to path do
	      content_tag :span, class: "glyphicon glyphicon-#{icon}" do
	        label
	      end
    	end
  	end

end


=begin
View Helper 的使用規則
雖然 View Helper 的方法寫在 app/helpers 目錄下的隨便哪個檔案都可以，但檔名以及模組名稱是有規則的：

模組名稱需為 XXXXHelper，例如 UserHelper 或是 PostHelper。
若模組名稱是 UserHelper，檔案名稱為 user_helper.rb；如果是 PostHelper，檔名則為 post_helper.rb，依此類推。
雖然 View Helper 的方法要寫在哪個 Helper 模組都可以，但模組會按照模組的名字的英文字母順序依序載入，例如 PostHelper 會比 UserHelper 先載入，
也就是說如果這兩個模組上有名字一樣的方法，先載入方法的會被後載入的覆蓋掉，這點需要特別注意。
=end

tdd/app/helpers/bmi_helper.rb
module BmiHelper
end

tdd/app/helpers/candidates_helper.rb
module CandidatesHelper
end

tdd/app/helpers/pages_helper.rb
module PagesHelper
end

tdd/app/views/bmi/index.html.erb
<h1>BMI calculator</h1>

<%= form_tag("/bmi/result") do %>
	身高: <%= text_field_tag ("body_height") %> 公分</br>
	體重: <%= text_field_tag ("body_weight") %> 公斤</br>
	年齡: <%= text_field_tag ("age")%> 歲</br>
	性別: <%= text_field_tag ("gender") %>男請輸入1, 女請輸入0</br>
	<%= submit_tag ("開始計算")%>
<%end %>

tdd/app/views/bmi/result.html.erb
你的 BMI為: <%= @bmi %></p>

你的體脂肪率為: <%= @fat_rate %> %</p>
體脂率公式如下:</p>
體脂率 = (1.2 * BMI) +(0.23 * 年齡 - 5.4) -(10.8 * 性別)</br>
其中男性=1,女性 = 0

tdd/app/views/candidates/_candidate.html.erb
<tr>
  <td><%= link_to "<span class='glyphicon glyphicon-knight'></span> 投給這位".html_safe, vote_candidate_path(candidate), method: "post", data: { confirm: "確認要投給這位候選人嗎?!" }, class: "btn btn-danger btn-xs" %></td>
  <td><%= candidate.name %>(年齡：<%= candidate.age %> 歲)</td>
  <td><%= candidate.party %></td>
  <td><%= candidate.politics %></td>
  <td><%= candidate.votes.size %></td>
  <td>
    <%= link_to "編輯", edit_candidate_path(candidate) %>
    <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除" } %>
  </td>
</tr>

tdd/app/views/candidates/_form.html.erb
<%= simple_form_for(candidate) do |f| %>
  <%= f.input :name, label: "姓名" %>
  <%= f.input :age, label: "年齡" %>
  <%= f.input :party, label: "政黨" %>
  <%= f.input :politics, label: "政見" %>
  <%= f.submit %>
<% end %>

tdd/app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render "form", candidate: @candidate %>

</br>

<%= link_to "回候選人列表" ,candidates_path %>

tdd/app/views/candidates/index.html.erb
<h1>候選人列表</h1>
<%= icon_link_to "新增候選人", new_candidate_path, "knight" %>

<table class = "table" >
	<thead>
		<tr>
			<td>投票</td>
			<td>候選人姓名</td>
      		<td>政黨</td>
      		<td>政見</td>
      		<td>得票數</td>
		</tr>
	</thead>

	<tbody>
	<%= render partial: "candidate", collection: @candidates %>
	<!-- 要再縮短可以改這樣 <%= render @candidates %> -->

	</tbody>
</table>


<!--
但這樣的寫法其實有點過於魔術，而且依賴不少 Rails 裡的「慣例」。如果要讓 <%= render @candidates %> 可以正常運作的話，需要完成以下幾件事：

局部樣版的檔名必須是那包資料的「單數」，以上面這個例子來說，那包資料叫做 @candidates，所以 Partial 的檔名就是 _candidate.html.erb。
局部樣版檔案必須而且放在對的位置，以這個例子來說，檔案是放在 app/views/candidates 目錄裡。
局部樣版裡不需要寫迴圈（寫了反而會多跑一層迴圈），裡面用到的區域變數必須是單數，例如 candidate。
如果沒有按照這些慣例就會出現找不到檔案或路徑的錯誤訊息。-->

tdd/app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form" , candidate: @candidate %>

</br>

<%= link_to "回候選人列表", candidates_path %>



tdd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tdd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= notice %>
  	<div class = container>
  		<%= yield %>
  	</div>
  </body>
</html>

tdd/app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>網站管理系統</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>我是後台</h1>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

tdd/app/views/pages/hello.html.erb
<h1>"Hello world!"</h1>
<h2>"Every designer can understand what I am write!"</h2>
